Replace use of apk-tools with apkq.
This reduces pollution of the test environment with
packages that are likely not installed at normal runtime.

While clealy 'apkq' is still a package, it has no other
dependencies and is not likely to be used elsewhere.

diff --git a/verify-service/verify-service b/verify-service/verify-service
--- a/verify-service/verify-service
+++ b/verify-service/verify-service
@@ -82,8 +82,13 @@ skip_expr="(${skip_expr})"
 
 echo "Package name: ${package_name}"
 echo "Skipping files: ${skip_expr}"
-service_files=$(mktemp)
-apk -L info ${package_name} | grep -E 'usr/lib/systemd/system/.*.(service|socket)$' | grep -vE "/${skip_expr}$" > ${service_files}
+service_files=$(mktemp) || error "mktemp failed"
+contents=$(mktemp) || error "mktemp failed"
+apkq info --contents --quiet "${package_name}" > "$contents" ||
+    error "apkq info ${package_name} failed"
+
+grep -E 'usr/lib/systemd/system/.*.(service|socket)$' "$contents" |
+    grep -vE "/${skip_expr}$" > ${service_files}
 
 if [ ! -s ${service_files} ]; then
 echo "No service or socket files found!"
@@ -94,4 +99,4 @@ for file in $(cat "${service_files}"); do
 systemd-analyze verify --man="${man}" "${file}"
 done
 
-rm "${service_files}"
+rm "${service_files}" "$contents"
